apiVersion: v1
kind: Secret
metadata:
  name: {{ include "arxiv-paper-rag.fullname" . }}-secret
  labels:
    {{- include "arxiv-paper-rag.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  POSTGRES_DB: {{ .Values.postgres.db | quote }}
  POSTGRES_DATABASE_URL: "postgresql+psycopg2://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@{{ include "arxiv-paper-rag.fullname" . }}-postgres:5432/{{ .Values.postgres.db }}"
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@{{ include "arxiv-paper-rag.fullname" . }}-postgres:5432/{{ .Values.postgres.db }}"

  # Langfuse Secrets
  LANGFUSE_POSTGRES_USER: {{ .Values.langfuse.postgres.user | quote }}
  LANGFUSE_POSTGRES_PASSWORD: {{ .Values.langfuse.postgres.password | quote }}
  LANGFUSE_POSTGRES_DB: {{ .Values.langfuse.postgres.db | quote }}
  LANGFUSE_DATABASE_URL: "postgresql://{{ .Values.langfuse.postgres.user }}:{{ .Values.langfuse.postgres.password }}@{{ include "arxiv-paper-rag.fullname" . }}-langfuse-postgres:5432/{{ .Values.langfuse.postgres.db }}"

  LANGFUSE_NEXTAUTH_SECRET: {{ .Values.langfuse.web.nextauthSecret | quote }}
  LANGFUSE_SALT: {{ .Values.langfuse.web.salt | quote }}
  LANGFUSE_ENCRYPTION_KEY: {{ .Values.langfuse.web.encryptionKey | quote }}
  LANGFUSE_REDIS_PASSWORD: {{ .Values.langfuse.redis.password | quote }}

  LANGFUSE_MINIO_USER: {{ .Values.langfuse.minio.rootUser | quote }}
  LANGFUSE_MINIO_PASSWORD: {{ .Values.langfuse.minio.rootPassword | quote }}

  CLICKHOUSE_USER: {{ .Values.clickhouse.user | quote }}
  CLICKHOUSE_PASSWORD: {{ .Values.clickhouse.password | quote }}

  # External Secrets
  JINA_API_KEY: {{ .Values.external.jinaApiKey | quote }}
  TELEGRAM__BOT_TOKEN: {{ .Values.external.telegram.botToken | quote }}
